### ISSUE TITLE
Navigation Hover

### ISSUE THREAD

**Issue by arniejolo** [arniejolo/kraken-good-accessibility#1]
@anna-pokhilenko
@thatkidmadrid

Hey guys, 
I'm having issues with getting the hover state for the navigation arrows to be thicker. I have tried changing the font-weight and targeting nav a in the hover state.  I was wondering if I need to target the .icon but I'm not sure what to put since it's not type.

**Comment by thatkidmadrid** [comment]
please ignore errors related to the new icon thickness, I quickly recreated them so they will not match exactly. I did not run into any errors when I used them so I didn't expect markbot to complain about them.

**Comment by thatkidmadrid** [comment]
could you please share a screenshot of what markbot was complaining about?

**Comment by arniejolo** [comment]
<img width="1447" alt="Screen Shot 2021-10-08 at 12 13 46 AM" src="https://user-images.githubusercontent.com/77504965/136497327-19a6aed4-5a8e-4227-ac8a-44b57e6050c0.png">

**Comment by arniejolo** [comment]
<img width="793" alt="Screen Shot 2021-10-08 at 12 14 42 AM" src="https://user-images.githubusercontent.com/77504965/136497386-a7975160-098d-4040-9a65-cdcf8938aa1d.png">

**Comment by arniejolo** [comment]
I will leave the navigation alone  – I just thought the thickness would have something to do with the 20% difference between the screenshots. 

I also do not understand what I'm doing wrong with the p, body and footer tags.

<img width="1289" alt="Screen Shot 2021-10-08 at 12 15 46 AM" src="https://user-images.githubusercontent.com/77504965/136497477-17cf840a-0575-422e-8b07-925d767f6275.png">

**Comment by thatkidmadrid** [comment]
ok, I'm not really sure what to add about the icons, but maybe fixing some other things will get the text to line up, and that may reduce the 20% more than changing the icons.

the selector `body > footer` means "a footer that is a direct child of the body" Although you have a footer, it is wrapped in an article so the selector cannot find the footer. One hint I can give you is that there are two footers to look out for. one with the navigation, and one with the copyright info. This means that you need to decide which footer gets the `contentinfo` role.

for the error on line `51`: you have the opening and closing `p` tags on a separate line from the text
```
51    <p> <!- opening p tag ->
52    For several days the Nautilus kept off from the American ...
53    </p> <!- closing p tag -> 
```

You can try having them all on the same line:
```
51    <p> For several days the Nautilus kept off from the American ... </p>
```

**Comment by thatkidmadrid** [comment]
Keep in mind that an `<article>` tag is meant to be used on content that can potentially stand alone. I see a few areas where you have articles used as a general wrapper like a `div` but you can include content that makes sense together within the same article tag. Just to simplify things I've provided a simpler structure that will work. 

You could make things a bit neater by following this structure:
```
<body>

    <header role="banner"></header>

    <article>

        <header>...</header>  <!- this contains the main navigation with the role="navigation" ->

        <div role="main">...</div> <!- this contains the actual chapter text ->

        <footer></footer> <!- this is the navigation footer ->

    </article>

    <footer role="contentinfo">...</footer>

</body>
```

Notice how, if you isolate the `<article>` it has a familiar header-content-footer structure and makes sense on its own.

Hope this helps with the structure so you can focus on the accessibility more. Try using Voiceover on your page, I see some problems that are easier to catch when you listen to it instead of reading your code

**Comment by arniejolo** [comment]
Thank you @thatkidmadrid ! The HTML structure you sent was very helpful!

Now I still have the <p> tag that Markbot says I need to have on the same line? There is a big paragraph that pushes my <p> out of the way when I try to type it in on the same line (51) – how would I go about inputing this?

**Comment by thatkidmadrid** [comment]
for the error on line `51`: you have the opening and closing `p` tags on a separate line from the text
```
51    <p> <!- opening p tag ->
52    For several days the Nautilus kept off from the American ...
53    </p> <!- closing p tag -> 
```

Try hitting backspace on the beginning of line `53`, then line `52` to have them all on the same line on `51`:
```
51    <p> For several days the Nautilus kept off from the American ... </p>
```

**Comment by arniejolo** [comment]
Thank you so much for your help Christian!
